# Generated by Django 4.1.1 on 2022-09-28 19:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dsc_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='created_at',
            new_name='created',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='body',
            new_name='description',
        ),
    ]
