# Generated by Django 4.1.1 on 2022-10-11 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dsc_app', '0002_rename_created_at_event_created_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='image',
            field=models.ImageField(default=True, upload_to='images/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='event',
            name='slug',
            field=models.SlugField(blank=True),
        ),
    ]
