# Generated by Django 4.1.1 on 2022-10-11 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dsc_app', '0003_event_image_event_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='image',
            field=models.ImageField(upload_to='images/%Y/%m/%d/'),
        ),
    ]
